services:
  rest:
    image: 'decision-support-web-backend:1.0.0'
    container_name: 'decision-support-rest-api'
    ports:
      - 8080:8080
      - 8000:8000
  uta-method:
    image: 'uta-method-service:1.0.0'
    container_name: 'uta-method-service'
    ports:
      - '8090:8000'
    depends_on:
      - rest
      