version: '3.0'

services:
  rest:
    image: 'decision-support-web-backend:1.0.0'
    container_name: 'decision-support-rest-api'
    ports:
      - '8000:8000'
  uta-method:
    image: 'uta_service:1.0.0'
    container_name: 'uta-method-service'
    ports:
      - '8090:8090'
    depends_on:
      - rest
  laravel:
    image: 'laravel-app:1.0.0'
    container_name: laravel-app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
      - '5173:5173'
    environment:
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}/../fullstack'
    volumes:
      - '../fullstack:/var/www/html'
    depends_on:
      - pgsql
  pgsql:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'mydatabase'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'
      - '../fullstack/vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
volumes:
  sail-pgsql:
    driver: local