FROM rstudio/plumber:v1.0.0

RUN mkdir /home/app
WORKDIR /home/app

COPY UTA.R /home/app/UTA.R

RUN apt-get update
RUN apt-get install -y libssl-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y build-essential
RUN apt-get install -y libcurl4-gnutls-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libsodium-dev
RUN apt-get install -y libglpk-dev
RUN apt-get install -y r-cran-httpuv
RUN apt-get install -y r-cran-plumber 

RUN R -e "install.packages('jsonlite')"
RUN R -e "install.packages('Rglpk')"

EXPOSE 8090 8000

CMD ["/home/app/UTA.R"]