name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Start PostgreSQL in Docker
        run: |
          docker-compose up -d postgres
          sleep 10
          
      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew test
          
      - name: Stop PostgreSQL Docker container
        run: docker-compose down

